Repository graphql-python/graphql-server, pull requests merged in 2020-07, with the labels that each got.

#45 Merge webob-graphql
  graphql_server/webob/__init__.py
  graphql_server/webob/graphqlview.py
  graphql_server/webob/render_graphiql.py
  setup.py
  tests/aiohttp/test_graphiqlview.py
  tests/webob/__init__.py
  tests/webob/app.py
  tests/webob/schema.py
  tests/webob/test_graphiqlview.py
  tests/webob/test_graphqlview.py
Labels: type: feature

#49 refactor: graphiql template shared across servers
  graphql_server/aiohttp/graphqlview.py
  graphql_server/aiohttp/render_graphiql.py
  graphql_server/flask/graphqlview.py
  graphql_server/flask/render_graphiql.py
  graphql_server/render_graphiql.py
  graphql_server/sanic/graphqlview.py
  graphql_server/sanic/render_graphiql.py
  graphql_server/webob/graphqlview.py
  graphql_server/webob/render_graphiql.py
  setup.py
  tests/aiohttp/test_graphiqlview.py
  tox.ini
Labels: type: maintenance

#50 Expose version number as __version__
  graphql_server/__init__.py
  graphql_server/version.py
  setup.py
  tests/__init__.py
  tests/test_version.py
Labels: type: maintenance

#53 Split parsing, validation and execution (#43)
  graphql_server/__init__.py
  tests/test_query.py
Labels: type: optimization, type: tests

#54 Docs about integration with each framework
  MANIFEST.in
  README.md
  docs/aiohttp.md
  docs/flask.md
  docs/sanic.md
  docs/webob.md
  graphql_server/flask/graphqlview.py
  graphql_server/sanic/graphqlview.py
  graphql_server/webob/graphqlview.py
Labels: type: documentation

#57 docs: add graphql-server logo
  MANIFEST.in
  README.md
  docs/_static/graphql-server-logo.svg
Labels: type: documentation

#58 chore: add GitHub Actions
  .github/workflows/deploy.yml
  .github/workflows/lint.yml
  .github/workflows/tests.yml
  .travis.yml
  tox.ini
Labels: type: chore

#55 Add graphiql options and missing flask context
  graphql_server/aiohttp/graphqlview.py
  graphql_server/flask/graphqlview.py
  graphql_server/render_graphiql.py
  graphql_server/sanic/graphqlview.py
  graphql_server/webob/graphqlview.py
  tests/aiohttp/schema.py
  tests/aiohttp/test_graphqlview.py
  tests/flask/schema.py
  tests/flask/test_graphqlview.py
  tests/sanic/schema.py
  tests/sanic/test_graphqlview.py
  tests/webob/schema.py
  tests/webob/test_graphqlview.py
Labels: type: bug, type: feature

#59 chore: rename to graphql-server and bump version
  CONTRIBUTING.md
  README.md
  docs/aiohttp.md
  docs/flask.md
  docs/sanic.md
  docs/webob.md
  graphql_server/__init__.py
  graphql_server/version.py
  setup.py
Labels: type: chore
