Repository graphql-python/graphql-server, pull requests merged in 2020-10, with the labels that each got.

#63 chore: submit coverage to codecov
  .github/workflows/lint.yml
  .github/workflows/tests.yml
Labels: type: chore

#67 Fix enable_async for aiohttp and sanic
  graphql_server/aiohttp/graphqlview.py
  graphql_server/sanic/graphqlview.py
  tests/aiohttp/schema.py
  tests/aiohttp/test_graphiqlview.py
  tests/sanic/schema.py
  tests/sanic/test_graphiqlview.py
Labels: type: bug

#71 chore: stable Python 3.9 support and bump version
  .github/workflows/tests.yml
  graphql_server/version.py
  setup.py
  tox.ini
Labels: type: chore

#73 Updated Optional Dependency: Sanic
  setup.py
Labels: type: maintenance
