Repository graphql-python/graphql-server, pull requests merged in 2020-05, with the labels that each got.

#37 Merge flask-graphql
  .gitignore
  graphql_server/__init__.py
  graphql_server/flask/__init__.py
  graphql_server/flask/graphqlview.py
  graphql_server/flask/render_graphiql.py
  setup.py
  tests/flask/__init__.py
  tests/flask/app.py
  tests/flask/schema.py
  tests/flask/test_graphiqlview.py
  tests/flask/test_graphqlview.py
Labels: type: feature

#40 Remove references to executor in Flask view
  graphql_server/flask/graphqlview.py
Labels: type: maintenance

#39 Return 200 errors
  graphql_server/__init__.py
  setup.py
  tests/flask/test_graphqlview.py
  tests/test_helpers.py
  tests/test_query.py
Labels: type: bug
